version: 2.1



jobs:
  
  failing_job:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: 
          command: return 1
      - run:
          name: error handling
          command: echo "error hndles succes"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - failing_job